import { validateContentV2 } from './evidence-validate';

// Noncanonical finite mechanic fixture. Never imported by the player barrel.
const result=validateContentV2({
  schemaVersion:2,id:'occasion-fixture',version:1,title:'Noncanonical authored occasions',start:'o0.arrival',
  occasions:[{id:'o0',label:'First visit'},{id:'o1',label:'After the return'},{id:'o2',label:'UNSEEN_OCCASION_LABEL'}],
  beliefIds:['anchor-belief','current-belief'],
  characters:[
    {id:'blaise',name:'Blaise',persistent:true,initial:{knows:[],believes:[],claims:[]}},
    {id:'miriam_exterior',name:'UNSEEN_EXTERIOR_NAME',persistent:true,requiresSnapshot:true,initial:{knows:[],believes:[],claims:[]}},
    {id:'o0.miriam',name:'Miriam',occasionId:'o0',initial:{knows:['o0.private-anchor'],believes:['anchor-belief'],claims:['o0.prior-claim']}},
    {id:'o1.miriam',name:'Miriam',occasionId:'o1',initial:{knows:['o1.private-anchor'],believes:['anchor-belief'],claims:[]}},
    {id:'o2.miriam',name:'Miriam',occasionId:'o2',initial:{knows:['o2.private-anchor'],believes:['anchor-belief'],claims:[]}},
    {id:'o1.simon',name:'Simon',occasionId:'o1',initial:{knows:[],believes:[],claims:[]}},
    {id:'o2.simon',name:'Simon',occasionId:'o2',initial:{knows:[],believes:[],claims:[]}},
  ],
  sources:[
    {id:'o0.film',occasionId:'o0',sourceKey:'incident-film',title:'Earlier recording',text:'An actually inspected recording. ORIGINAL_FILM_TEXT',kind:'document',provenanceId:'incident-film'},
    {id:'o0.ring',occasionId:'o0',title:'Dry ring',text:'The earlier ring was dry.',kind:'observation',provenanceId:'ring-inspection'},
    {id:'o0.rinse',occasionId:'o0',title:'Rinse test',text:'The earlier water left the same ring.',kind:'observation',provenanceId:'rinse-test'},
    {id:'o0.private-anchor',occasionId:'o0',title:'PRIVATE_TITLE',text:'UNSEEN_NPC_ANCHOR_SECRET',kind:'document',provenanceId:'anchor-private'},
    {id:'o1.private-anchor',occasionId:'o1',title:'PRIVATE_TITLE',text:'UNSEEN_NPC_ANCHOR_SECRET',kind:'document',provenanceId:'anchor-private'},
    {id:'o2.private-anchor',occasionId:'o2',title:'PRIVATE_TITLE',text:'UNSEEN_NPC_ANCHOR_SECRET',kind:'document',provenanceId:'anchor-private'},
    {id:'o0.prior-claim',occasionId:'o0',title:'Private prior claim',text:'UNSEEN_PRIOR_CLAIM',kind:'statement',speakerId:'o0.miriam',provenanceId:'shared-incident-account'},
    {id:'o0.confidence',occasionId:'o0',title:'Actually heard confidence',text:'A private confidence actually delivered to Blaise.',kind:'statement',speakerId:'o0.miriam',provenanceId:'private-conversation'},
    {id:'o0.chair-contact',occasionId:'o0',title:'Chair contact',text:'Blaise hears the exact words at the chair.',kind:'observation',provenanceId:'blaise-chair-contact'},
    {id:'o0.chair-distant',occasionId:'o0',title:'UNSEEN_WITNESS_TITLE',text:'UNSEEN_WITNESS_SECRET: Miriam saw movement without hearing the words.',kind:'observation',provenanceId:'miriam-chair-observation'},
    {id:'o0.marked-object',occasionId:'o0',title:'Marked exterior object',text:'A mark is made and the object placed outside.',kind:'observation',provenanceId:'object-preparation'},
    {id:'o0.front-departure',occasionId:'o0',title:'Observed front departure',text:'Miriam goes out through the front before the service crossing.',kind:'observation',provenanceId:'front-departure'},
    {id:'o0.service-crossing',occasionId:'o0',title:'Service crossing',text:'Cardboard catches at the handle.',kind:'observation',provenanceId:'first-service-crossing'},
    {id:'o1.tableau',occasionId:'o1',title:'Current tableau',text:'The renewed interior has the anchor arrangement.',kind:'observation',provenanceId:'first-return'},
    {id:'o1.film',occasionId:'o1',sourceKey:'incident-film',title:'Currently inspected recording',text:'A present inspection of the same originating recording. CURRENT_FILM_TEXT',kind:'document',provenanceId:'incident-film'},
    {id:'o1.memory-film',occasionId:'o1',title:'Told from memory',text:'Blaise explicitly recalls the earlier film; he does not show it.',kind:'statement',speakerId:'blaise',provenanceId:'fresh-report-must-not-be-an-origin',derivedFrom:['o0.film']},
    {id:'o1.memory-finding',occasionId:'o1',title:'Remembered finding',text:'Blaise recounts the finding with its actual earlier support.',kind:'statement',speakerId:'blaise',provenanceId:'fresh-finding-report',derivedFrom:['o0.finding']},
    {id:'o1.photo',occasionId:'o1',title:'New photograph',text:'A different actually encountered current observation.',kind:'document',provenanceId:'new-camera-origin'},
    {id:'o1.interior-testimony',occasionId:'o1',title:'Bench account',text:'The bench speaker recalls the pre-anchor incident.',kind:'statement',speakerId:'o1.miriam',provenanceId:'shared-incident-account'},
    {id:'o1.exterior-testimony',occasionId:'o1',title:'Doorway account',text:'The doorway speaker recalls the same pre-anchor incident.',kind:'statement',speakerId:'miriam_exterior',provenanceId:'shared-incident-account'},
    {id:'o1.exterior-chair-account',occasionId:'o1',title:'Bounded chair account',text:'She remembers movement, without inventing exact words.',kind:'statement',speakerId:'miriam_exterior',provenanceId:'miriam-chair-observation'},
    {id:'o1.current-fact',occasionId:'o1',title:'Current comparison',text:'A current comparison is shown to the exterior speaker.',kind:'observation',provenanceId:'current-comparison'},
    {id:'o1.second-disclosure',occasionId:'o1',title:'Discussed second trial',text:'Blaise describes the bounded risk before an optional empty-handed trial.',kind:'statement',speakerId:'blaise',provenanceId:'trial-disclosure',derivedFrom:['o1.tableau']},
    {id:'o1.second-crossing',occasionId:'o1',title:'Empty-handed crossing',text:'The second service crossing is actually selected without the parcel.',kind:'observation',provenanceId:'second-service-crossing'},
    {id:'o2.tableau',occasionId:'o2',title:'Second current tableau',text:'The second renewed tableau is actually encountered.',kind:'observation',provenanceId:'second-return'},
  ],
  questions:[
    {id:'o0.finding',occasionId:'o0',text:'Record the bounded earlier finding.',candidates:[{id:'supported',text:'The selected observations support this account.'}],supportedCandidateId:'supported',proof:{op:'any',args:[{op:'ref',refId:'o0.film',scope:'current'},{op:'all',args:[{op:'ref',refId:'o0.ring',scope:'current'},{op:'ref',refId:'o0.rinse',scope:'current'}]}]},allowedCorroborators:[],feedback:[],effects:['o0.found']},
    {id:'o1.current-film',occasionId:'o1',text:'Which material is currently inspected?',candidates:[{id:'supported',text:'A current inspection is recorded.'}],supportedCandidateId:'supported',proof:{op:'ref',refId:'o1.film',scope:'current'},allowedCorroborators:[],feedback:[]},
    {id:'o1.historical-film',occasionId:'o1',text:'Which material was earlier encountered?',candidates:[{id:'supported',text:'An earlier inspection is remembered.'}],supportedCandidateId:'supported',proof:{op:'ref',refId:'o0.film',scope:'historical'},allowedCorroborators:[],feedback:[]},
    {id:'o1.independent-film',occasionId:'o1',text:'Do these selected accounts have independent origins?',candidates:[{id:'supported',text:'Two independent origins are selected.'}],supportedCandidateId:'supported',proof:{op:'all',independent:true,args:[{op:'ref',refId:'o0.film',scope:'historical'},{op:'any',args:[{op:'ref',refId:'o1.memory-film',scope:'current'},{op:'ref',refId:'o1.film',scope:'current'},{op:'ref',refId:'o1.photo',scope:'current'}]}]},allowedCorroborators:[],feedback:[]},
    {id:'o1.independent-finding',occasionId:'o1',text:'Does a new report add an origin?',candidates:[{id:'supported',text:'An independent new origin is selected.'}],supportedCandidateId:'supported',proof:{op:'all',independent:true,args:[{op:'ref',refId:'o0.finding',scope:'historical'},{op:'any',args:[{op:'ref',refId:'o1.memory-finding',scope:'current'},{op:'ref',refId:'o1.photo',scope:'current'}]}]},allowedCorroborators:[],feedback:[]},
    {id:'o1.independent-speakers',occasionId:'o1',text:'Do the speakers add independent prior observations?',candidates:[{id:'supported',text:'Independent originating observations are selected.'}],supportedCandidateId:'supported',proof:{op:'all',independent:true,args:[{op:'ref',refId:'o1.interior-testimony',scope:'current'},{op:'any',args:[{op:'ref',refId:'o1.exterior-testimony',scope:'current'},{op:'ref',refId:'o1.photo',scope:'current'}]}]},allowedCorroborators:[],feedback:[]},
    {id:'o2.question',occasionId:'o2',text:'UNSEEN_FUTURE_QUESTION',candidates:[{id:'supported',text:'The second tableau is recorded.'}],supportedCandidateId:'supported',proof:{op:'ref',refId:'o2.tableau',scope:'current'},allowedCorroborators:[],feedback:[]},
  ],
  interpretationRules:[
    {id:'o0.reading',occasionId:'o0',title:'Reconsider the earlier film',text:'Only this actually selected reading is captured. OLD_READING_TEXT',when:{op:'hasSource',id:'o0.film',scope:'current'},relatedRefs:['o0.film'],effects:['o0.reading-ready']},
    {id:'o0.late-reading',occasionId:'o0',title:'UNSEEN_OLD_UNEARNED_READING',text:'UNSEEN_OLD_UNEARNED_PROSE',when:{op:'hasSource',id:'o0.rinse',scope:'current'},relatedRefs:['o0.rinse'],effects:['o0.late-ready']},
    {id:'o2.reading',occasionId:'o2',title:'UNSEEN_FUTURE_READING',text:'The second visited tableau supports a new possible reading.',when:{op:'hasSource',id:'o2.tableau',scope:'current'},relatedRefs:['o2.tableau'],effects:['o2.reading-ready']},
  ],
  hints:[
    {id:'o0.hint',occasionId:'o0',label:'Consider earlier evidence',questionId:'o0.finding',when:{op:'hasSource',id:'o0.film',scope:'current'},mentions:['o0.film'],text:'The earlier source remains unchanged.',reveals:false},
    {id:'o2.hint',occasionId:'o2',label:'UNSEEN_FUTURE_HINT',questionId:'o2.question',when:{op:'hasSource',id:'o2.tableau',scope:'current'},mentions:['o2.tableau'],text:'The later source is current only now.',reveals:false},
  ],
  scenes:[
    {id:'o0.arrival',occasionId:'o0',title:'First arrival',paragraphs:['Only the actual first arrival is captured. ORIGINAL_OCCASION_TEXT'],sourceIds:['o0.ring'],choices:[
      {id:'inspect-old-film',label:'Inspect the earlier recording.',target:'o0.arrival',actions:[{type:'acquireSource',sourceId:'o0.film'}]},
      {id:'test-old-rinse',label:'Perform the earlier rinse test.',target:'o0.arrival',actions:[{type:'acquireSource',sourceId:'o0.rinse'}]},
      {id:'hear-confidence',label:'Hear the actual private confidence.',target:'o0.arrival',actions:[{type:'acquireSource',sourceId:'o0.confidence'}],effects:['o0.heard-private']},
      {id:'refuse-confidence',label:'Decline the private conversation.',target:'o0.arrival',effects:['o0.refused-private'],unless:['o0.heard-private']},
      {id:'tell-first-finding',label:'Tell the first speaker the selected finding.',target:'o0.arrival',when:{op:'hasDeduction',id:'o0.finding',scope:'current'},actions:[{type:'disclose',characterId:'o0.miriam',refId:'o0.finding'}]},
      {id:'prepare-chair',label:'Perform the chair event and mark the exterior object.',target:'o0.departure',actions:[{type:'acquireSource',sourceId:'o0.chair-contact'},{type:'witnessSource',characterId:'o0.miriam',sourceId:'o0.chair-distant'},{type:'setBelief',characterId:'o0.miriam',beliefId:'current-belief',value:true}],effects:['o0.chair-performed']},
    ]},
    {id:'o0.departure',occasionId:'o0',title:'Observed departure',paragraphs:['The marking and custody are actually performed.'],sourceIds:['o0.marked-object'],choices:[{id:'front-departure',label:'Watch the front departure.',target:'o0.crossing',actions:[{type:'acquireSource',sourceId:'o0.front-departure'},{type:'witnessSource',characterId:'o0.miriam',sourceId:'o0.front-departure'},{type:'snapshotCharacter',fromCharacterId:'o0.miriam',toCharacterId:'miriam_exterior'}],effects:['o0.departed']}]},
    {id:'o0.crossing',occasionId:'o0',title:'The service handle',paragraphs:['Blaise carries the weight. The wrapping catches. BEFORE_CROSSING_TEXT'],choices:[{id:'first-crossing',label:'Take the weight through the service door.',target:'o1.arrival',enterOccasion:'o1',actions:[{type:'acquireSource',sourceId:'o0.service-crossing'}],effects:['o0.crossed']}]},
    {id:'o1.arrival',occasionId:'o1',title:'Renewed arrival',when:{op:'occasionIs',id:'o1'},paragraphs:['The handle is empty. Only the renewed tableau is delivered. RETURN_OCCASION_TEXT'],sourceIds:['o1.tableau'],choices:[
      {id:'inspect-current-film',label:'Actually inspect the present recording.',target:'o1.arrival',actions:[{type:'acquireSource',sourceId:'o1.film'}]},
      {id:'recall-film',label:'Describe the earlier recording from memory.',target:'o1.arrival',when:{op:'hasSource',id:'o0.film',scope:'historical'},actions:[{type:'acquireSource',sourceId:'o1.memory-film'}]},
      {id:'recall-finding',label:'Describe the earlier accepted finding from memory.',target:'o1.arrival',when:{op:'hasDeduction',id:'o0.finding',scope:'historical'},actions:[{type:'acquireSource',sourceId:'o1.memory-finding'}]},
      {id:'tell-simon-memory',label:'Tell Simon the current recollection.',target:'o1.arrival',when:{op:'hasSource',id:'o1.memory-film',scope:'current'},actions:[{type:'disclose',characterId:'o1.simon',refId:'o1.memory-film'}]},
      {id:'new-photo',label:'Inspect the new photograph.',target:'o1.arrival',actions:[{type:'acquireSource',sourceId:'o1.photo'}]},
      {id:'meet-speakers',label:'Actually hear both speakers and the bounded chair account.',target:'o1.arrival',when:{op:'npcKnows',characterId:'miriam_exterior',refId:'o0.chair-distant'},actions:[{type:'acquireSource',sourceId:'o1.interior-testimony'},{type:'acquireSource',sourceId:'o1.exterior-testimony'},{type:'acquireSource',sourceId:'o1.exterior-chair-account'}]},
      {id:'tell-exterior-current',label:'Show the exterior speaker the current comparison.',target:'o1.arrival',actions:[{type:'acquireSource',sourceId:'o1.current-fact'},{type:'disclose',characterId:'miriam_exterior',refId:'o1.current-fact'}]},
      {id:'discuss-second-trial',label:'Discuss the optional second trial with its actual audience.',target:'o1.arrival',actions:[{type:'acquireSource',sourceId:'o1.second-disclosure'},{type:'disclose',characterId:'miriam_exterior',refId:'o1.second-disclosure'}],effects:['o1.informed']},
      {id:'second-crossing',label:'Choose the empty-handed second service crossing.',target:'o2.arrival',enterOccasion:'o2',requires:['o1.informed'],when:{op:'npcKnows',characterId:'miriam_exterior',refId:'o1.second-disclosure'},irreversible:true,actions:[{type:'acquireSource',sourceId:'o1.second-crossing'}]},
      {id:'decline-second',label:'Decline another service trial and leave through the front.',target:'o1.refusal',ending:true},
    ]},
    {id:'o1.refusal',occasionId:'o1',title:'A refusal ending',paragraphs:['No second occasion is asserted on this route.'],choices:[]},
    {id:'o2.arrival',occasionId:'o2',title:'Another renewed arrival',when:{op:'occasionIs',id:'o2'},paragraphs:['The empty-handed return is now actually encountered. SECOND_OCCASION_TEXT'],sourceIds:['o2.tableau'],choices:[{id:'finish-second',label:'Finish the bounded observed second trial.',target:'o2.ending',ending:true}]},
    {id:'o2.ending',occasionId:'o2',title:'Second-trial ending',paragraphs:['The fixture makes no universal claim about another crossing.'],choices:[]},
  ],
});
if(!result.ok)throw new Error(result.errors.join('\n'));
export const occasionFixture=result.value;
