import { useRef, useState } from 'react';
import { App, download } from './App';
import { initialContent } from './content/load';
import { contentHash, validateContent, type Choice, type Content } from './engine/game';
import { contentSchema } from './engine/schema';
import { GameStore } from './persistence/store';
import { StudioDraftStore } from './persistence/studio';

const draftStore = new StudioDraftStore(), previewStore = new GameStore(globalThis.indexedDB,'literary-detective-studio-preview-v1');
const listFlags = (value: string) => value.split(',').map(flag => flag.trim()).filter(Boolean);
export function Studio() {
  const [acknowledged,setAcknowledged] = useState(false), [draft,setDraft] = useState<Content>(() => structuredClone(initialContent)), [lastValid,setLastValid] = useState(initialContent);
  const [selected,setSelected] = useState(initialContent.start), [view,setView] = useState<'editor'|'preview'>('editor'), [status,setStatus] = useState('Edits remain in memory until you save a studio draft or download JSON.');
  const [generation,setGeneration] = useState(0), [raw,setRaw] = useState(''), [transaction,setTransaction] = useState('Initial content');
  const undo = useRef<{content:Content,label:string}[]>([]), redo = useRef<{content:Content,label:string}[]>([]);
  const result = validateContent(draft), scene = draft.scenes.find(s => s.id === selected) ?? draft.scenes[0];
  function adopt(next: Content,label: string) { setDraft(next); setSelected(current => next.scenes.some(s => s.id === current) ? current : next.start); setGeneration(g => g+1); setTransaction(label); const valid = validateContent(next); if (valid.ok) setLastValid(valid.value); }
  function edit(label: string,mutate: (next: Content) => void) { const next = structuredClone(draft); mutate(next); if (JSON.stringify(next) === JSON.stringify(draft)) return; undo.current.push({content:draft,label:transaction}); if (undo.current.length > 100) undo.current.shift(); redo.current = []; adopt(next,label); }
  function history(direction:'undo'|'redo') { const from = direction === 'undo' ? undo.current : redo.current, to = direction === 'undo' ? redo.current : undo.current, previous = from.pop(); if (!previous) return; to.push({content:draft,label:transaction}); adopt(previous.content,previous.label); }
  function importContent(text: string) { try { const parsed: unknown = JSON.parse(text), shape = contentSchema.safeParse(parsed); if (!shape.success) { setStatus(`Import rejected: ${shape.error.issues.slice(0,8).map(issue => `${issue.path.join('.')}: ${issue.message}`).join('; ')}`); return; } edit('Import content',next => Object.assign(next,shape.data)); setStatus('Imported content. Check diagnostics before preview or export.'); } catch { setStatus('Import rejected: the file is not valid JSON.'); } }
  function changeChoice(index:number,label:string,mutate:(choice:Choice)=>void) { edit(label,next => mutate(next.scenes.find(s => s.id === scene.id)!.choices[index])); }
  function addScene() { let suffix=1; while(draft.scenes.some(s => s.id === `scene.${suffix}`)) suffix++; const id=`scene.${suffix}`; edit('Add scene',next => next.scenes.push({id,title:'New scene',paragraphs:['Draft a passage here.'],choices:[]})); setSelected(id); }
  function deleteScene() { const references = draft.scenes.flatMap(s => s.choices.filter(c => c.target === scene.id && s.id !== scene.id).map(c=>c.id)); if(scene.id === draft.start || references.length) { setStatus(`Cannot delete ${scene.id}. ${scene.id === draft.start ? 'Select a different start scene first.' : `Redirect incoming choices first: ${references.join(', ')}.`}`); return; } edit('Delete unreferenced scene',next => { next.scenes = next.scenes.filter(s => s.id !== scene.id); }); }
  return <><header className="site-header"><div><p className="eyebrow">Separate author application · spoilers</p><h1>Text studio</h1></div></header><main className="studio-main">
    <p>The studio edits the real JSON content contract. It includes every passage and ending. Its drafts and preview saves use separate browser databases.</p><label className="checkbox"><input type="checkbox" checked={acknowledged} onChange={e=>setAcknowledged(e.target.checked)} /> I want to view author content and spoilers.</label>
    {acknowledged && <><div className="toolbar"><button onClick={()=>setView('editor')}>Edit content</button><button onClick={()=>setView('preview')}>Preview last valid content</button><button disabled={!undo.current.length} onClick={()=>history('undo')}>Undo</button><button disabled={!redo.current.length} onClick={()=>history('redo')}>Redo</button><button onClick={()=>{ void draftStore.save(draft,lastValid).then(()=>setStatus('Studio draft saved in its separate browser database.')).catch(()=>setStatus('Studio save failed. The active draft remains in memory; download it before closing.')); }}>Save studio draft</button><button onClick={()=>{ void draftStore.load(draft.id).then(saved=>{ if(!saved){setStatus('No saved studio draft for this project.');return;} undo.current.push({content:draft,label:transaction});redo.current=[];adopt(saved.draft,'Load saved studio draft');setLastValid(saved.lastValid);setStatus('Studio draft loaded.'); }).catch(()=>setStatus('Studio load failed validation or storage access. Your active draft remains in memory.')); }}>Load studio draft</button><button onClick={()=>download(`${draft.id}-draft.json`,JSON.stringify(draft,null,2))}>Download draft JSON</button><label className="file-label">Import content<input type="file" accept=".json,application/json" onChange={async e=>{ const file=e.target.files?.[0]; if(!file)return;if(file.size>10*1024*1024){setStatus('Import rejected: exceeds 10 MB.');return;}importContent(await file.text());e.target.value=''; }} /></label></div>
    <p className="studio-status" role="status">{status}</p><section className="diagnostics" aria-label="Content diagnostics"><h2>Diagnostics</h2>{result.ok?<p>Current content passes the implemented schema and graph checks.</p>:<><p>The draft is invalid. Preview retains the last valid content.</p><ul>{result.errors.map((error,index)=><li key={index}>{error}</li>)}</ul></>}<p>Last editor transaction: {transaction}. Static graph checks do not prove every gated route. This bounded format does not yet implement the full baseline deduction DSL.</p></section>
    {view==='preview'?<><p className="warning">Spoiler-aware author preview. {result.ok?'This preview uses validated current content.':'This preview uses the last valid content, not the broken draft.'}</p><App key={contentHash(lastValid)} suppliedContent={lastValid} persistence={previewStore} preview /></>:<div className="studio-grid" key={`${generation}:${scene.id}`}>
      <aside className="studio-sidebar"><h2>Project</h2><label>Title<input defaultValue={draft.title} onBlur={e=>edit('Edit project title',next=>{next.title=e.target.value;})}/></label><label>Content version<input type="number" min="1" defaultValue={draft.version} onBlur={e=>edit('Edit content version',next=>{next.version=Number(e.target.value);})}/></label><p>Project ID: <code>{draft.id}</code></p><label>Start scene<select value={draft.start} onChange={e=>edit('Change start scene',next=>{next.start=e.target.value;})}>{draft.scenes.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>Scene<select value={scene.id} onChange={e=>setSelected(e.target.value)}>{draft.scenes.map(s=><option key={s.id} value={s.id}>{s.title} ({s.id})</option>)}</select></label><div className="toolbar"><button onClick={addScene}>Add scene</button><button onClick={deleteScene}>Delete unreferenced scene</button></div><p>IDs stay stable. Redirect references before deleting. Form edits commit on leaving a field; undo reverses each committed edit.</p></aside>
      <section className="studio-editor"><h2>Edit scene</h2><p>ID: <code>{scene.id}</code></p><label>Scene title<input defaultValue={scene.title} onBlur={e=>edit('Edit scene title',next=>{next.scenes.find(s=>s.id===scene.id)!.title=e.target.value;})}/></label><label>Scene required flags, comma separated<input defaultValue={scene.requires?.join(', ')??''} onBlur={e=>edit('Edit scene gate',next=>{next.scenes.find(s=>s.id===scene.id)!.requires=listFlags(e.target.value);})}/></label><h3>Paragraphs</h3>{scene.paragraphs.map((paragraph,index)=><div className="paragraph-editor" key={index}><label>Paragraph {index+1}<textarea defaultValue={paragraph} onBlur={e=>edit('Edit paragraph',next=>{next.scenes.find(s=>s.id===scene.id)!.paragraphs[index]=e.target.value;})}/></label><button className="quiet" disabled={scene.paragraphs.length<=1} onClick={()=>edit('Remove paragraph',next=>{next.scenes.find(s=>s.id===scene.id)!.paragraphs.splice(index,1);})}>Remove paragraph {index+1}</button></div>)}<button onClick={()=>edit('Add paragraph',next=>next.scenes.find(s=>s.id===scene.id)!.paragraphs.push('New paragraph.'))}>Add paragraph</button>
      <h3>Choices</h3>{scene.choices.map((choice,index)=><fieldset key={choice.id}><legend>{choice.id}</legend><label>Visible action label<input defaultValue={choice.label} onBlur={e=>changeChoice(index,'Edit choice label',c=>{c.label=e.target.value;})}/></label><label>Target scene<select value={choice.target} onChange={e=>changeChoice(index,'Change choice destination',c=>{c.target=e.target.value;})}>{draft.scenes.map(s=><option key={s.id} value={s.id}>{s.title} ({s.id})</option>)}</select></label>{(['requires','unless','effects'] as const).map(field=><label key={field}>{field}, comma separated<input defaultValue={choice[field]?.join(', ')??''} onBlur={e=>changeChoice(index,`Edit choice ${field}`,c=>{c[field]=listFlags(e.target.value);})}/></label>)}{(['observation','interpretation','relationship'] as const).map(field=><label key={field}>{field} text<textarea defaultValue={choice[field]?.text??''} onBlur={e=>changeChoice(index,`Edit ${field}`,c=>{if(e.target.value.trim())c[field]={id:c[field]?.id??`${c.id}.${field}`,text:e.target.value};else delete c[field];})}/></label>)}<label className="checkbox"><input type="checkbox" checked={choice.ending??false} onChange={e=>changeChoice(index,'Change ending status',c=>{c.ending=e.target.checked;})}/> Ends the run</label><label className="checkbox"><input type="checkbox" checked={choice.irreversible??false} onChange={e=>changeChoice(index,'Change confirmation requirement',c=>{c.irreversible=e.target.checked;})}/> Requires interpersonal action confirmation</label><button className="quiet" onClick={()=>edit('Remove choice',next=>{next.scenes.find(s=>s.id===scene.id)!.choices.splice(index,1);})}>Remove choice</button></fieldset>)}<button onClick={()=>{const all=new Set(draft.scenes.flatMap(s=>s.choices.map(c=>c.id)));let number=1;while(all.has(`${scene.id}.choice.${number}`))number++;edit('Add choice',next=>next.scenes.find(s=>s.id===scene.id)!.choices.push({id:`${scene.id}.choice.${number}`,label:'Describe the action taken.',target:scene.id}));}}>Add choice</button>
      <h3>Dependency table</h3><table><thead><tr><th>Choice</th><th>Destination</th><th>Requires</th><th>Adds</th></tr></thead><tbody>{scene.choices.map(c=><tr key={c.id}><td>{c.id}</td><td>{c.target}</td><td>{c.requires?.join(', ')||'None'}</td><td>{c.effects?.join(', ')||'None'}</td></tr>)}</tbody></table>
      <details><summary>Advanced JSON editing, including variants</summary><p>Paste the entire content document. Validated imports preserve the same format as structured edits.</p><button onClick={()=>setRaw(JSON.stringify(draft,null,2))}>Copy draft into JSON editor</button><label>Content JSON<textarea className="raw-editor" value={raw} onChange={e=>setRaw(e.target.value)} spellCheck={false}/></label><button onClick={()=>importContent(raw)}>Import editor JSON as a transaction</button></details></section>
    </div>}</>}
  </main></>;
}
