import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
const base=process.env.PLAYER_TEST_URL??'http://localhost:4183';
const studio=process.env.STUDIO_TEST_URL??'http://localhost:4184/studio.html';
const folder='docs/execution/evidence/browser';mkdirSync(folder,{recursive:true});
const content=JSON.parse(readFileSync('src/content/case.json','utf8'));
const actions=new Map(content.scenes.flatMap(s=>s.choices.map(c=>[c.id,c])));
const report={status:'RUNNING',scope:'Chromium on cloud Linux; real controls/engine/IndexedDB; simulated execution, no human playtime or screen-reader claim',builtManifest:JSON.parse(readFileSync('dist-player/asset-manifest.json','utf8')),sourceCaseSha256:createHash('sha256').update(readFileSync('src/content/case.json')).digest('hex'),checks:[],consoleErrors:[],pageErrors:[],notTested:['Firefox','WebKit','real assistive technology','human playtime','all editor operations','compatible cross-version migration']};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});
const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))report.consoleErrors.push(m.text());});
async function check(name,fn){try{const detail=await fn();report.checks.push({name,status:'PASS',detail});}catch(error){report.checks.push({name,status:'FAIL',error:String(error)});throw error;}}
async function saved(p=page){await expect(p.locator('.save-status')).toContainText(/^(Progress saved|Saved progress loaded|The newest save was damaged|No saved run)/,{timeout:15000});}
async function keyboardActivate(button,p=page){for(let i=0;i<150;i++){if(await button.evaluate(el=>document.activeElement===el)){await p.keyboard.press('Enter');return;}await p.keyboard.press('Tab');}throw new Error('Action not keyboard reachable');}
async function choose(id,p=page,keyboard=true){const a=actions.get(id);if(!a)throw new Error(`Unknown test action ${id}`);const button=p.getByRole('button',{name:a.label,exact:true});await expect(button).toBeEnabled();if(keyboard)await keyboardActivate(button,p);else await button.click();if(a.ending||a.irreversible){await expect(p.getByRole('dialog')).toBeVisible();if(keyboard)await keyboardActivate(p.getByRole('button',{name:'Confirm action',exact:true}),p);else await p.getByRole('button',{name:'Confirm action',exact:true}).click();}await saved(p);}
try{
 await check('Initial player and spoiler boundaries',async()=>{await page.goto(base);await expect(page.locator('#passage-title')).toBeVisible();await expect(page.locator('body')).not.toContainText('Text studio');await expect(page.locator('body')).not.toContainText('Four plates');return {heading:await page.locator('#passage-title').innerText()};});
 await check('Responsive layouts and enlarged text',async()=>{const sizes=[[1440,900],[1280,800],[390,844],[320,740]];for(const [width,height]of sizes){await page.setViewportSize({width,height});await page.screenshot({path:`${folder}/player-${width}.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}await page.getByLabel('Text size').selectOption('large');await page.evaluate(()=>document.documentElement.style.zoom='2');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`${folder}/player-zoom.png`});await page.evaluate(()=>document.documentElement.style.zoom='');await page.setViewportSize({width:1440,height:900});return {sizes,zoom:'CSS 200%, plus large text; not a physical-device check'};});
 await check('Automated player accessibility scan',async()=>{const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();writeFileSync(`${folder}/axe-player.json`,JSON.stringify(result,null,2));expect(result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.length}))).toEqual([]);return {violations:0,incomplete:result.incomplete.length};});
 await check('Keyboard investigation and reload',async()=>{for(const id of ['arrival-cabinet','cabinet-infer','hub-gallery','gallery-recording','recording-keep'])await choose(id);const before=await page.locator('#passage-title').innerText();await page.reload();await saved();expect(await page.locator('#passage-title').innerText()).toBe(before);return {actions:5,heading:before};});
 await check('Real stale-tab write preserves newer progress',async()=>{const other=await context.newPage();await other.goto(base);await saved(other);await choose('hub-shared');await choose('hub-bench',other,false).catch(()=>undefined);await expect(other.locator('.save-status')).toContainText('Another tab');await expect(other.getByRole('button',{name:'I understand. Continue without saving.'})).toBeVisible();await page.reload();await saved();expect(await page.locator('#passage-title').innerText()).toBe(content.scenes.find(s=>s.id==='shared').title);await other.close();return 'Second tab could not overwrite the shared-scene save.';});
 await check('Keyboard disclosure and closing route',async()=>{for(const id of ['shared-optics','optics-narrow','cabinet-report','report-public','public-next','continue-stay'])await choose(id);await expect(page.locator('.ending-note')).toBeVisible();await page.getByText(/Read encountered transcript/).click();await expect(page.locator('.transcript')).not.toHaveCount(0);return {ending:await page.locator('#passage-title').innerText()};});
 await check('Player export contains encountered text only',async()=>{const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export encountered run',exact:true}).click();const dl=await downloadEvent;const path=`${folder}/encountered-run.json`;await dl.saveAs(path);const parsed=JSON.parse(readFileSync(path,'utf8'));expect(parsed.state.ended).toBe(true);const original=content.scenes.find(s=>s.id==='arrival').paragraphs;expect(parsed.state.transcript[0].paragraphs).toEqual(original);expect(JSON.stringify(parsed)).not.toContain('The mirror will keep');return {revision:parsed.state.revision,passages:parsed.state.transcript.filter(x=>x.kind==='passage').length};});
 await check('New run archives prior completed run',async()=>{await page.getByText('Start or import a run',{exact:true}).click();await page.getByRole('button',{name:'Start a new run',exact:true}).click();await page.getByRole('button',{name:'Confirm action',exact:true}).click();await saved();expect(await page.locator('#passage-title').innerText()).toBe(content.scenes[0].title);const summary=page.getByText(/Archived runs \(/);await summary.click();await expect(page.getByRole('button',{name:'Load as a branch'}).first()).toBeVisible();return await summary.innerText();});
 await check('Installed built app reloads and plays offline',async()=>{await expect(page.locator('.offline-status')).toContainText('Ready for offline play',{timeout:15000});await context.setOffline(true);await page.reload();await saved();await choose('arrival-miriam');await expect(page.locator('#passage-title')).toHaveText(content.scenes.find(s=>s.id==='bench').title);await context.setOffline(false);return 'Offline shell, content, choices and local saves work.';});
 await check('Corrupted cache cannot claim offline ready',async()=>{await page.evaluate(async()=>{const name=(await caches.keys()).find(x=>x.startsWith('literary-detective-'));const cache=await caches.open(name);const req=(await cache.keys()).find(x=>x.url.endsWith('.css'));if(!req)throw Error('No cached style');await cache.put(req,new Response('corrupted cached bytes',{headers:{'content-type':'text/css'}}));});await page.reload();await expect(page.locator('.offline-status')).toContainText(/incomplete|failed|not be verified/,{timeout:15000});return await page.locator('.offline-status').innerText();});
 await check('Separate studio structured edit, undo and preview',async()=>{const author=await browser.newContext({viewport:{width:1280,height:800}});const p=await author.newPage();await p.goto(studio);await p.getByLabel('I want to view author content and spoilers.').check();const title=p.getByLabel('Scene title',{exact:true});const before=await title.inputValue();await title.fill('A browser edit');await title.press('Tab');await expect(p.getByLabel('Scene title',{exact:true})).toHaveValue('A browser edit');await p.getByRole('button',{name:'Undo',exact:true}).click();await expect(p.getByLabel('Scene title',{exact:true})).toHaveValue(before);await p.getByRole('button',{name:'Preview last valid content',exact:true}).click();await expect(p.locator('#passage-title')).toBeVisible();await p.screenshot({path:`${folder}/studio-preview.png`});const violations=(await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa']).analyze()).violations.map(v=>({id:v.id,impact:v.impact}));writeFileSync(`${folder}/axe-studio-violations.json`,JSON.stringify(violations,null,2));await author.close();return {structuredEdit:true,undo:true,preview:true,axeViolations:violations};});
 const studioCheck=report.checks.find(x=>x.name==='Separate studio structured edit, undo and preview');
 if(studioCheck)expect(studioCheck.detail.axeViolations).toEqual([]);
 expect(report.pageErrors).toEqual([]);
 report.status=report.checks.some(x=>x.status==='FAIL')?'FAIL':'PASS';
}catch(error){report.status='FAIL';report.failure=String(error);}finally{await browser.close();report.sourceCaseSha256After=createHash('sha256').update(readFileSync('src/content/case.json')).digest('hex');report.sourceStable=report.sourceCaseSha256After===report.sourceCaseSha256;writeFileSync(`${folder}/report.json`,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(report.status==='FAIL')process.exitCode=1;}
